// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfG3QC19nks0rxb-FJKYoplDxhYjegH7M',
    appId: '1:657668157743:web:78547e448d91644a30b1da',
    messagingSenderId: '657668157743',
    projectId: 'kitap-rotam',
    authDomain: 'kitap-rotam.firebaseapp.com',
    storageBucket: 'kitap-rotam.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjCvDCTdRwZzviz28G23AfaSNqHmG-DQ',
    appId: '1:657668157743:android:eb7039ccba049c3e30b1da',
    messagingSenderId: '657668157743',
    projectId: 'kitap-rotam',
    storageBucket: 'kitap-rotam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsnJkZXUuXvquPqdfQ-M1fzF0GBt6lQJA',
    appId: '1:657668157743:ios:45e1b66bd35787ad30b1da',
    messagingSenderId: '657668157743',
    projectId: 'kitap-rotam',
    storageBucket: 'kitap-rotam.appspot.com',
    iosBundleId: 'com.example.kitap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsnJkZXUuXvquPqdfQ-M1fzF0GBt6lQJA',
    appId: '1:657668157743:ios:eb8248a8963e77e430b1da',
    messagingSenderId: '657668157743',
    projectId: 'kitap-rotam',
    storageBucket: 'kitap-rotam.appspot.com',
    iosBundleId: 'com.example.kitap.RunnerTests',
  );
}
